// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfdIui_qJ5wkexxl1HoOx4ADRYorxw2m8',
    appId: '1:834761131244:web:310ba5aedb0775c575d1c9',
    messagingSenderId: '834761131244',
    projectId: 'aokauthentication',
    authDomain: 'aokauthentication.firebaseapp.com',
    storageBucket: 'aokauthentication.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHESQHu_QZGT7CZeo2zNppWdjRdQgj264',
    appId: '1:834761131244:android:26388f45ecd543cf75d1c9',
    messagingSenderId: '834761131244',
    projectId: 'aokauthentication',
    storageBucket: 'aokauthentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7mvMZOU5tGAguKF7QO-wIvqxxaR390M',
    appId: '1:834761131244:ios:6518e19f1c09d24175d1c9',
    messagingSenderId: '834761131244',
    projectId: 'aokauthentication',
    storageBucket: 'aokauthentication.appspot.com',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa7mvMZOU5tGAguKF7QO-wIvqxxaR390M',
    appId: '1:834761131244:ios:aed1dabc3c1afb4b75d1c9',
    messagingSenderId: '834761131244',
    projectId: 'aokauthentication',
    storageBucket: 'aokauthentication.appspot.com',
    iosBundleId: 'com.example.a.RunnerTests',
  );
}
